name: Build Madlib Project
description: Build and test a Madlib project
inputs:
  madlibVersion:
    description: What version of Madlib should be used?
    default: 'latest'
    required: false
  testLLVM:
    description: Should we test Madlib in LLVM mode?
    default: ''
    required: false
  testJS:
    description: Should we test Madlib in JS mode?
    default: ''
    required: false
  coverage:
    description: Should we capture test coverage?
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - name: 🛒 Checking out Madlib repo...
      uses: actions/checkout@v4
    - name: ⚙️  Installing node...
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 😈 Setting up Madlib project... 
      shell: bash
      run: |
        npm install -g @madlib-lang/madlib@${{github.event.inputs.madlibVersion}}
        echo "Madlib installed!"
        echo "Madlib version:"
        madlib -v
        echo "... ${{github.events.inputs.testLLVM}} <> ${{github.events.inputs.testJS}} <> ${{github.events.inputs.coverage}}" 
        ${{ !github.event.inputs.testLLVM && !github.events.inputs.coverage && '' || github.event.inputs.testLLVM && !github.events.inputs.coverage && 'madlib test --target llvm' || 'madlib test --target llvm --coverage'}}
        ${{ !github.event.inputs.testJS && !github.events.inputs.coverage && '' || github.event.inputs.testJS && !github.events.inputs.coverage && 'madlib test --target node' || 'madlib test --target node --coverage'}}
