name: Build Madlib Project
description: Build and test a Madlib project
inputs:
  madlibVersion:
    description: What version of Madlib should be used?
    default: 'latest'
    required: false
  testLLVM:
    description: Should we test Madlib in LLVM mode?
    default: ''
    type: boolean
    required: false
  testJS:
    description: Should we test Madlib in JS mode?
    default: ''
    type: boolean
    required: false
  coverage:
    description: Should we capture test coverage?
    default: ''
    type: boolean
    required: false

runs:
  using: 'composite'
  steps:
    - name: 🛒 Checking out Madlib repo...
      uses: actions/checkout@v4
    - name: ⚙️  Installing node...
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: 😈 Setting up Madlib project... 
      shell: bash
      run: |
        npm install -g @madlib-lang/madlib@${{github.event.inputs.madlibVersion}}
        echo "Madlib installed!"
        echo "Madlib version:"
        madlib -v
    - name: "🧪 Testing Madlib, target: LLVM"
      shell: bash
      if: github.event.inputs.testLLVM
      run: madlib test --target llvm ${{!github.event.inputs.coverage && '' || '--coverage'}}
    - name: "⚗️  Testing Madlib, target: JS"
      if: github.event.inputs.testJS
      shell: bash
      run: madlib test --target llvm ${{!github.event.inputs.coverage && '' || '--coverage'}}
